stages:
  - lint
  - test
  - verify

lint-job:
  stage: lint
  image: alpine:latest
  script:
    - echo "Lint passed!"

test-job:
  stage: test
  image: alpine:latest
  script:
    - echo "Test passed!"

verify-job:
  stage: verify
  image: alpine:latest
  script:
    - echo "Verify passed!"
